// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SimpleCNMessageProto.proto

package com.lxn.netty.model.protoModel;

public final class SimpleCNMessageProto {
  private SimpleCNMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SimpleCNMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lxn.netty.model.protoModel.SimpleCNMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required string string_text = 2;</code>
     */
    boolean hasStringText();
    /**
     * <code>required string string_text = 2;</code>
     */
    java.lang.String getStringText();
    /**
     * <code>required string string_text = 2;</code>
     */
    com.google.protobuf.ByteString
        getStringTextBytes();

    /**
     * <code>required bytes bytes_text = 3;</code>
     */
    boolean hasBytesText();
    /**
     * <code>required bytes bytes_text = 3;</code>
     */
    com.google.protobuf.ByteString getBytesText();
  }
  /**
   * Protobuf type {@code com.lxn.netty.model.protoModel.SimpleCNMessage}
   */
  public  static final class SimpleCNMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lxn.netty.model.protoModel.SimpleCNMessage)
      SimpleCNMessageOrBuilder {
    // Use SimpleCNMessage.newBuilder() to construct.
    private SimpleCNMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimpleCNMessage() {
      id_ = 0L;
      stringText_ = "";
      bytesText_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SimpleCNMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              stringText_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              bytesText_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lxn.netty.model.protoModel.SimpleCNMessageProto.internal_static_com_lxn_netty_model_protoModel_SimpleCNMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lxn.netty.model.protoModel.SimpleCNMessageProto.internal_static_com_lxn_netty_model_protoModel_SimpleCNMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage.class, com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int STRING_TEXT_FIELD_NUMBER = 2;
    private volatile java.lang.Object stringText_;
    /**
     * <code>required string string_text = 2;</code>
     */
    public boolean hasStringText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string string_text = 2;</code>
     */
    public java.lang.String getStringText() {
      java.lang.Object ref = stringText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stringText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string string_text = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStringTextBytes() {
      java.lang.Object ref = stringText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BYTES_TEXT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString bytesText_;
    /**
     * <code>required bytes bytes_text = 3;</code>
     */
    public boolean hasBytesText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes bytes_text = 3;</code>
     */
    public com.google.protobuf.ByteString getBytesText() {
      return bytesText_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStringText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBytesText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stringText_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, bytesText_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stringText_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, bytesText_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage)) {
        return super.equals(obj);
      }
      com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage other = (com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasStringText() == other.hasStringText());
      if (hasStringText()) {
        result = result && getStringText()
            .equals(other.getStringText());
      }
      result = result && (hasBytesText() == other.hasBytesText());
      if (hasBytesText()) {
        result = result && getBytesText()
            .equals(other.getBytesText());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasStringText()) {
        hash = (37 * hash) + STRING_TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getStringText().hashCode();
      }
      if (hasBytesText()) {
        hash = (37 * hash) + BYTES_TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getBytesText().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lxn.netty.model.protoModel.SimpleCNMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lxn.netty.model.protoModel.SimpleCNMessage)
        com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lxn.netty.model.protoModel.SimpleCNMessageProto.internal_static_com_lxn_netty_model_protoModel_SimpleCNMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lxn.netty.model.protoModel.SimpleCNMessageProto.internal_static_com_lxn_netty_model_protoModel_SimpleCNMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage.class, com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage.Builder.class);
      }

      // Construct using com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        stringText_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        bytesText_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lxn.netty.model.protoModel.SimpleCNMessageProto.internal_static_com_lxn_netty_model_protoModel_SimpleCNMessage_descriptor;
      }

      public com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage getDefaultInstanceForType() {
        return com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage.getDefaultInstance();
      }

      public com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage build() {
        com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage buildPartial() {
        com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage result = new com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.stringText_ = stringText_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.bytesText_ = bytesText_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage) {
          return mergeFrom((com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage other) {
        if (other == com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasStringText()) {
          bitField0_ |= 0x00000002;
          stringText_ = other.stringText_;
          onChanged();
        }
        if (other.hasBytesText()) {
          setBytesText(other.getBytesText());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasStringText()) {
          return false;
        }
        if (!hasBytesText()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object stringText_ = "";
      /**
       * <code>required string string_text = 2;</code>
       */
      public boolean hasStringText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string string_text = 2;</code>
       */
      public java.lang.String getStringText() {
        java.lang.Object ref = stringText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stringText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string string_text = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStringTextBytes() {
        java.lang.Object ref = stringText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string string_text = 2;</code>
       */
      public Builder setStringText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        stringText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string string_text = 2;</code>
       */
      public Builder clearStringText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stringText_ = getDefaultInstance().getStringText();
        onChanged();
        return this;
      }
      /**
       * <code>required string string_text = 2;</code>
       */
      public Builder setStringTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        stringText_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytesText_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes bytes_text = 3;</code>
       */
      public boolean hasBytesText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes bytes_text = 3;</code>
       */
      public com.google.protobuf.ByteString getBytesText() {
        return bytesText_;
      }
      /**
       * <code>required bytes bytes_text = 3;</code>
       */
      public Builder setBytesText(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        bytesText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes bytes_text = 3;</code>
       */
      public Builder clearBytesText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bytesText_ = getDefaultInstance().getBytesText();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lxn.netty.model.protoModel.SimpleCNMessage)
    }

    // @@protoc_insertion_point(class_scope:com.lxn.netty.model.protoModel.SimpleCNMessage)
    private static final com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage();
    }

    public static com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SimpleCNMessage>
        PARSER = new com.google.protobuf.AbstractParser<SimpleCNMessage>() {
      public SimpleCNMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SimpleCNMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SimpleCNMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleCNMessage> getParserForType() {
      return PARSER;
    }

    public com.lxn.netty.model.protoModel.SimpleCNMessageProto.SimpleCNMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lxn_netty_model_protoModel_SimpleCNMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lxn_netty_model_protoModel_SimpleCNMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032SimpleCNMessageProto.proto\022\036com.lxn.ne" +
      "tty.model.protoModel\"F\n\017SimpleCNMessage\022" +
      "\n\n\002id\030\001 \002(\003\022\023\n\013string_text\030\002 \002(\t\022\022\n\nbyte" +
      "s_text\030\003 \002(\014B\026B\024SimpleCNMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lxn_netty_model_protoModel_SimpleCNMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lxn_netty_model_protoModel_SimpleCNMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lxn_netty_model_protoModel_SimpleCNMessage_descriptor,
        new java.lang.String[] { "Id", "StringText", "BytesText", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
